<a href="https://colab.research.google.com/github/Minal-2007/PROJECTS-/blob/main/Automobile_complaint_analyzer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install nltk scikit-learn

Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.3.3)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)

In [ ]:
import pandas as pd
import numpy as np
import nltk
import pickle
import string

In [ ]:
from nltk.corpus import stopwords

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score , classification_report

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [ ]:
df = pd.read_excel('/content/automobile_complaint_dataset.xlsx')

In [ ]:
df.head()

,Complaint_ID,Customer_Name,Vehicle_Model,Fuel_Type,Complaint_Text,Technical_System,Probable_Issue,Severity_Level,Service_Department,Complaint_Date
0,CMP10000,Courtney Kirk,Toyota Innova,Petrol,My vehicle has an issue where air conditioner ...,HVAC,compressor fault,Medium,HVAC Service,2026-04-20
1,CMP10001,Denise Foster,MG ZS EV,Diesel,My vehicle has an issue where gear shifting be...,Transmission,transmission fluid issue,High,Transmission Service,2025-09-01
2,CMP10002,Ricardo Cook,Mahindra XUV700,EV,My vehicle has an issue where heater not worki...,HVAC,heater core issue,Medium,HVAC Service,2025-07-06
3,CMP10003,Jonathan Wood,Skoda Slavia,EV,My vehicle has an issue where battery drains o...,Battery,battery degradation,High,Battery Service,2026-01-11
4,CMP10004,Joann Hernandez,Skoda Slavia,Diesel,My vehicle has an issue where headlights dim w...,Electrical,electrical grounding issue,High,Electrical Service,2025-07-24

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Complaint_ID        1200 non-null   object
 1   Customer_Name       1200 non-null   object
 2   Vehicle_Model       1200 non-null   object
 3   Fuel_Type           1200 non-null   object
 4   Complaint_Text      1200 non-null   object
 5   Technical_System    1200 non-null   object
 6   Probable_Issue      1200 non-null   object
 7   Severity_Level      1200 non-null   object
 8   Service_Department  1200 non-null   object
 9   Complaint_Date      1200 non-null   object
dtypes: object(10)
memory usage: 93.9+ KB

In [ ]:
x=df['Complaint_Text']

In [ ]:
y_system = df['Technical_System']

In [ ]:
y_severity = df['Severity_Level']

In [ ]:
stop_words = set (stopwords.words('english'))

In [ ]:
def clean_text(text) :
  text=text.lower()
  text = ''.join(char for char in text if char not in string.punctuation)
  text=text.split()
  text = [word for word in text if word not in stop_words]
  return ' '.join(text)

In [ ]:
x_clean = x.apply(clean_text)

In [ ]:
tfidf_vectorizer = TfidfVectorizer()
x_tfidf = tfidf_vectorizer.fit_transform(x_clean)

In [ ]:
X_train_system, X_test_system, y_train_system, y_test_system = train_test_split(x_tfidf, y_system, test_size=0.2, random_state=42)

In [ ]:
X_train_severity, X_test_severity, y_train_severity, y_test_severity = train_test_split(x_tfidf, y_severity, test_size=0.2, random_state=42)

In [ ]:
x_clean.head()

0    vehicle issue air conditioner cooling properly...
1    vehicle issue gear shifting becomes difficult ...
2    vehicle issue heater working rain especially rain
3    vehicle issue battery drains overnight high speed
4    vehicle issue headlights dim driving especiall...
Name: Complaint_Text, dtype: object

In [ ]:
vectorizer = TfidfVectorizer()
x_tfidf = vectorizer.fit_transform(x_clean)

In [ ]:
X_train, X_test, y_train_system, y_test_system = train_test_split(
    x_tfidf,
    y_system,
    test_size=0.2,
    random_state=42
)

_, _, y_train_severity, y_test_severity = train_test_split(
    x_tfidf,
    y_severity,
    test_size=0.2,
    random_state=42
)

In [ ]:
model_system = LogisticRegression(max_iter=1000)
model_system.fit(X_train, y_train_system)

LogisticRegression(max_iter=1000)

In [ ]:
model_severity = LogisticRegression(max_iter=1000)
model_severity.fit(X_train, y_train_severity)

LogisticRegression(max_iter=1000)

In [ ]:
y_pred_system = model_system.predict(X_test)

In [ ]:
print("Technical System Model Performance:")
print(f"Accuracy: {accuracy_score(y_test_system, y_pred_system):.4f}")
print("Classification Report:")
print(classification_report(y_test_system, y_pred_system))

Technical System Model Performance:
Accuracy: 1.0000
Classification Report:
              precision    recall  f1-score   support

     Battery       1.00      1.00      1.00        35
     Braking       1.00      1.00      1.00        34
  Electrical       1.00      1.00      1.00        38
      Engine       1.00      1.00      1.00        26
        HVAC       1.00      1.00      1.00        27
    Steering       1.00      1.00      1.00        30
  Suspension       1.00      1.00      1.00        19
Transmission       1.00      1.00      1.00        31

    accuracy                           1.00       240
   macro avg       1.00      1.00      1.00       240
weighted avg       1.00      1.00      1.00       240

In [ ]:
y_pred_severity = model_severity.predict(X_test)

In [ ]:
print("Severity Level Model Performance:")
print(f"Accuracy: {accuracy_score(y_test_severity, y_pred_severity):.4f}")
print("Classification Report:")
print(classification_report(y_test_severity, y_pred_severity))

Severity Level Model Performance:
Accuracy: 1.0000
Classification Report:
              precision    recall  f1-score   support

    Critical       1.00      1.00      1.00        28
        High       1.00      1.00      1.00       109
         Low       1.00      1.00      1.00        22
      Medium       1.00      1.00      1.00        81

    accuracy                           1.00       240
   macro avg       1.00      1.00      1.00       240
weighted avg       1.00      1.00      1.00       240

In [ ]:
system_model = LogisticRegression(max_iter=1000)
system_model.fit(X_train,y_train_system)

LogisticRegression(max_iter=1000)

In [ ]:
system_predictions = system_model.predict(X_test)
severity_predictions = model_severity.predict(X_test)

In [ ]:
print("SYSTEM MODEL ACCURACY")
print(accuracy_score(y_test_system, system_predictions))

print("\nSYSTEM CLASSIFICATION REPORT")
print(classification_report(y_test_system, system_predictions))

SYSTEM MODEL ACCURACY
1.0

SYSTEM CLASSIFICATION REPORT
              precision    recall  f1-score   support

     Battery       1.00      1.00      1.00        35
     Braking       1.00      1.00      1.00        34
  Electrical       1.00      1.00      1.00        38
      Engine       1.00      1.00      1.00        26
        HVAC       1.00      1.00      1.00        27
    Steering       1.00      1.00      1.00        30
  Suspension       1.00      1.00      1.00        19
Transmission       1.00      1.00      1.00        31

    accuracy                           1.00       240
   macro avg       1.00      1.00      1.00       240
weighted avg       1.00      1.00      1.00       240

In [ ]:
print("SEVERITY MODEL ACCURACY")
print(accuracy_score(y_test_severity, severity_predictions))

print("\nSEVERITY CLASSIFICATION REPORT")
print(classification_report(y_test_severity, severity_predictions))

SEVERITY MODEL ACCURACY
1.0

SEVERITY CLASSIFICATION REPORT
              precision    recall  f1-score   support

    Critical       1.00      1.00      1.00        28
        High       1.00      1.00      1.00       109
         Low       1.00      1.00      1.00        22
      Medium       1.00      1.00      1.00        81

    accuracy                           1.00       240
   macro avg       1.00      1.00      1.00       240
weighted avg       1.00      1.00      1.00       240

In [ ]:
sample_complaint = [
    "Brake pedal becomes hard during highway driving"
]

sample_clean = [clean_text(text) for text in sample_complaint]

sample_vector = vectorizer.transform(sample_clean)

predicted_system = system_model.predict(sample_vector)

predicted_severity = model_severity.predict(sample_vector)

print("Predicted System:", predicted_system[0])

print("Predicted Severity:", predicted_severity[0])

Predicted System: Braking
Predicted Severity: High

In [ ]:
probabilities = system_model.predict_proba(sample_vector)

classes = system_model.classes_

for label, prob in zip(classes, probabilities[0]):
    print(label, ":", round(prob * 100, 2), "%")

Battery : 1.23 %
Braking : 90.63 %
Electrical : 1.47 %
Engine : 1.07 %
HVAC : 1.11 %
Steering : 1.53 %
Suspension : 1.16 %
Transmission : 1.81 %

In [ ]:
pickle.dump(system_model, open('system_model.pkl', 'wb'))

pickle.dump(model_severity, open('severity_model.pkl', 'wb'))

pickle.dump(vectorizer, open('vectorizer.pkl', 'wb'))

In [ ]:
from google.colab import files

files.download('system_model.pkl')
files.download('severity_model.pkl')
files.download('vectorizer.pkl')

In [ ]:
!pip install flask flask-ngrok

Requirement already satisfied: flask in /usr/local/lib/python3.12/dist-packages (3.1.3)
Collecting flask-ngrok
  Downloading flask_ngrok-0.0.25-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: blinker>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from flask) (1.9.0)
Requirement already satisfied: click>=8.1.3 in /usr/local/lib/python3.12/dist-packages (from flask) (8.3.3)
Requirement already satisfied: itsdangerous>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from flask) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in /usr/local/lib/python3.12/dist-packages (from flask) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from flask) (3.0.3)
Requirement already satisfied: werkzeug>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from flask) (3.1.8)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from flask-ngrok) (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->flask-ngrok) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->flask-ngrok) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->flask-ngrok) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->flask-ngrok) (2026.4.22)
Downloading flask_ngrok-0.0.25-py3-none-any.whl (3.1 kB)
Installing collected packages: flask-ngrok
Successfully installed flask-ngrok-0.0.25

In [ ]:
from flask import Flask, request, jsonify

import pickle

import string

from nltk.corpus import stopwords
from threading import Thread

In [ ]:
system_model = pickle.load(open('system_model.pkl', 'rb'))

severity_model = pickle.load(open('severity_model.pkl', 'rb'))

vectorizer = pickle.load(open('vectorizer.pkl', 'rb'))

In [ ]:
app = Flask(__name__)

In [ ]:
stop_words = set(stopwords.words('english'))

def clean_text(text):

    text = text.lower()

    text = ''.join(char for char in text if char not in string.punctuation)

    words = text.split()

    words = [word for word in words if word not in stop_words]

    return ' '.join(words)

In [ ]:
@app.route('/predict', methods=['POST'])

def predict():

    data = request.get_json()

    complaint = data['complaint']

    cleaned = clean_text(complaint)

    vector = vectorizer.transform([cleaned])

    probabilities = system_model.predict_proba(vector)

    confidence = max(probabilities[0]) * 100

    system_prediction = system_model.predict(vector)[0]

    severity_prediction = severity_model.predict(vector)[0]

    response = {
        'technical_system': system_prediction,
        'severity': severity_prediction,
        'confidence_score': round(confidence, 2)
    }

    return jsonify(response)

In [ ]:
!pip install flask

Requirement already satisfied: flask in /usr/local/lib/python3.12/dist-packages (3.1.3)
Requirement already satisfied: blinker>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from flask) (1.9.0)
Requirement already satisfied: click>=8.1.3 in /usr/local/lib/python3.12/dist-packages (from flask) (8.3.3)
Requirement already satisfied: itsdangerous>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from flask) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in /usr/local/lib/python3.12/dist-packages (from flask) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from flask) (3.0.3)
Requirement already satisfied: werkzeug>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from flask) (3.1.8)

In [ ]:
def run_app():
    app.run(host='0.0.0.0', port=5000)

thread = Thread(target=run_app)

thread.start()

In [ ]:
import requests

url = "http://127.0.0.1:5000/predict"

data = {
    "complaint": "Brake pedal becomes hard during highway driving"
}

response = requests.post(url, json=data)

print(response.json())

INFO:werkzeug:127.0.0.1 - - [13/May/2026 11:35:33] "POST /predict HTTP/1.1" 200 -

{'confidence_score': 90.63, 'severity': 'High', 'technical_system': 'Braking'}