<a href="https://colab.research.google.com/github/Minal-2007/PROJECTS-/blob/main/Drone_fault_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [5]:
import joblib

In [6]:
df = pd.read_csv("/content/drone_fault_dataset.csv")

In [7]:
df.head()

      acc_x     acc_y      acc_z  ...  voltage  temperature          label
0 -0.050616  0.319419   9.812409  ...    12.44        55.49    motor_fault
1 -0.057597 -0.492134  10.441122  ...    11.62        61.49    motor_fault
2  0.006335 -0.148144   9.903174  ...    12.27        56.03    motor_fault
3  0.147640 -0.409270   9.719674  ...    12.57        51.59    motor_fault
4 -0.082023 -0.028481   9.477950  ...    10.72        39.38  battery_fault

[5 rows x 10 columns]

In [11]:
df.shape

(1000, 10)

In [12]:
df.info(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   acc_x        1000 non-null   float64
 1   acc_y        1000 non-null   float64
 2   acc_z        1000 non-null   float64
 3   gyro_x       1000 non-null   float64
 4   gyro_y       1000 non-null   float64
 5   gyro_z       1000 non-null   float64
 6   rpm          1000 non-null   int64
 7   voltage      1000 non-null   float64
 8   temperature  1000 non-null   float64
 9   label        1000 non-null   object
dtypes: float64(8), int64(1), object(1)
memory usage: 78.3+ KB

In [13]:
df["label"].value_counts()

label
motor_fault      250
battery_fault    250
vibration        250
normal           250
Name: count, dtype: int64

In [14]:
label = LabelEncoder()

In [16]:
df["label"]=label.fit_transform(df["label"])

In [18]:
print(label.classes_)

['battery_fault' 'motor_fault' 'normal' 'vibration']

In [19]:
X = df.drop("label",axis=1)

In [20]:
y=df["label"]

In [21]:
print(X.head())
print(y.head())

      acc_x     acc_y      acc_z  ...   rpm  voltage  temperature
0 -0.050616  0.319419   9.812409  ...  2259    12.44        55.49
1 -0.057597 -0.492134  10.441122  ...  2464    11.62        61.49
2  0.006335 -0.148144   9.903174  ...  1612    12.27        56.03
3  0.147640 -0.409270   9.719674  ...  1599    12.57        51.59
4 -0.082023 -0.028481   9.477950  ...  4948    10.72        39.38

[5 rows x 9 columns]
0    1
1    1
2    1
3    1
4    0
Name: label, dtype: int64

In [22]:
X_train,X_test,y_train,y_test = train_test_split (X,y,test_size=0.2,random_state=42)

In [23]:
print(X_train.shape)
print(X_test.shape)

(800, 9)
(200, 9)

In [26]:
model = RandomForestClassifier(n_estimators=100, random_state=42)

In [27]:
model.fit(X_train,y_train)

RandomForestClassifier(random_state=42)

In [28]:
predictions = model.predict(X_test)

In [30]:
accuracy = accuracy_score(y_test,predictions)

In [31]:
print("Accuracy:",accuracy)

Accuracy: 1.0

In [32]:
cm = confusion_matrix (y_test,predictions)

In [33]:
print(cm)

[[42  0  0  0]
 [ 0 49  0  0]
 [ 0  0 58  0]
 [ 0  0  0 51]]

In [34]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        42
           1       1.00      1.00      1.00        49
           2       1.00      1.00      1.00        58
           3       1.00      1.00      1.00        51

    accuracy                           1.00       200
   macro avg       1.00      1.00      1.00       200
weighted avg       1.00      1.00      1.00       200

In [35]:
joblib.dump(model,"drone.model.pkl")

['drone.model.pkl']

In [37]:
joblib.dump(label,"label_encoder.pkl")

['label_encoder.pkl']